//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpotPdiPartStatus60
    {
        public long id { get; set; }
        public Nullable<long> SequenceNo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Shift { get; set; }
        public string Barcode { get; set; }
        public string Inspect { get; set; }
        public string Point1 { get; set; }
        public string Point2 { get; set; }
        public string Point3 { get; set; }
        public string Point4 { get; set; }
        public string Point5 { get; set; }
        public string Point6 { get; set; }
        public string Point7 { get; set; }
        public string Point8 { get; set; }
        public string Point9 { get; set; }
        public string Point10 { get; set; }
        public string Point11 { get; set; }
        public string Point12 { get; set; }
        public string Point13 { get; set; }
        public string Point14 { get; set; }
        public string Point15 { get; set; }
        public string Point16 { get; set; }
        public string Point17 { get; set; }
        public string Point18 { get; set; }
        public string Point19 { get; set; }
        public string Point20 { get; set; }
        public string Point21 { get; set; }
        public string Point22 { get; set; }
        public string Point23 { get; set; }
        public string Point24 { get; set; }
        public string Point25 { get; set; }
        public string Point26 { get; set; }
        public string Point27 { get; set; }
        public string Point28 { get; set; }
        public string Point29 { get; set; }
        public string Point30 { get; set; }
        public string Point31 { get; set; }
        public string Point32 { get; set; }
        public string Point33 { get; set; }
        public string Point34 { get; set; }
        public string Point35 { get; set; }
        public string Point36 { get; set; }
        public string Point37 { get; set; }
        public string Point38 { get; set; }
        public string Point39 { get; set; }
        public string Point40 { get; set; }
        public string Point41 { get; set; }
        public string Point42 { get; set; }
        public string Point43 { get; set; }
        public string Point44 { get; set; }
        public string Point45 { get; set; }
        public string Point46 { get; set; }
        public string Point47 { get; set; }
        public string Point48 { get; set; }
        public string Point49 { get; set; }
        public string Point50 { get; set; }
        public string Point51 { get; set; }
        public string Point52 { get; set; }
        public string Point53 { get; set; }
        public string Point54 { get; set; }
        public string Point55 { get; set; }
        public string Point56 { get; set; }
        public string Point57 { get; set; }
    }
}
